joy:
    ros__parameters:
      deadzone: 0.01
      autorepeat_rate: 20.0
      coalesce_interval_ms: 1
      sticky_buttons: True

joy_command:
  ros__parameters:
    joy_topic: "joy"
    depth_topic: "depth_sensor"
    pose_topic: "set_pose"
    twist_topic: "set_twist"
    publish_rate: 100
    imu_topic: "imu"
    multiplier: 1.0
    cmd_pub_topic: "command"
    axis_mapping.linear_x: 3
    axis_mapping.linear_y: 4
    axis_mapping.linear_z: 1
    axis_mapping.angular_x: 7
    axis_mapping.angular_y: 6
    axis_mapping.angular_z: 0
    using_joy: True
    using_ekf: True