thruster_manager:
  ros__parameters:
    num_motors: 8
    motor0:
      surge: -0.1116
      sway: -0.5393  
      heave: 0.0 
      roll: 0.0 
      pitch: 0.0 
      yaw: -0.0010 

    motor1:
      surge: -0.7071
      sway: -0.7071
      heave: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.0

    motor2:
      surge: -0.6329
      sway: -0.1116
      heave: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: -0.0012

    motor3:
      surge: 0.1858
      sway: -0.2794 
      heave: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: -0.0001 

    motor4:
      surge: 0.0359
      sway: 0.0408
      heave: 0.2500
      roll: 0.0011
      pitch: -0.0009
      yaw: 0.0

    motor5:
      surge: 0.0359
      sway: -0.0408
      heave: -0.2500
      roll: -0.0011
      pitch: -0.0009
      yaw: 0.0

    motor6:
      surge: -0.0359
      sway: -0.0408 
      heave: 0.2500 
      roll: -0.0011
      pitch: 0.0009 
      yaw: 0.0 

    motor7:
      surge: -0.0359
      sway: 0.0408 
      heave: 0.2500 
      roll: 0.0011
      pitch: 0.0009 
      yaw: 0.0 