thruster_manager:
  ros__parameters:
    max_force: 100.0
    max_torque: 30.0
    num_motors: 8

    motor2:
      surge: 0.0360
      sway: 0.0409
      heave: 0.2500
      roll: 1.0723
      pitch: -0.9438
      yaw: 0.0

    motor3:
      surge: 0.0360
      sway: -0.0409
      heave: -0.2500
      roll: -1.0723
      pitch: -0.9438
      yaw: 0.0

    motor4:
      surge: -0.0360
      sway: 0.0409
      heave: -0.2500
      roll: 1.0723
      pitch: 0.9438
      yaw: 0.0

    motor5:
      surge: -0.3536
      sway: 0.3536
      heave: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.5651

    motor6:
      surge: -0.3536
      sway: -0.3536
      heave: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.5651

    motor7:
      surge: 0.0360
      sway: -0.0409
      heave: 0.2500
      roll: -1.0723
      pitch: 0.9438
      yaw: 0.0

    motor0:
      surge: 0.3536
      sway: 0.3536
      heave: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.5651
    
    motor1:
      surge: 0.3536
      sway: -0.3536
      heave: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 0.5651
