ekf_node:
  ros__parameters:

    use_sim_time: true
    frequency: 10.0
    publish_tf: true
    odom_frame : muuv/odom
    world_frame : muuv/odom
    # map_frame : muuv/map
    base_link_frame : muuv/base_link
    sensor_timeout : 1.0
    imu0 : imu_data/raw
    imu0_config : [false, false, false, 
                  true, true, true, 
                  false, false, false, 
                  true, true, true, 
                  true, true, true]
    imu0_queue_size : 2
    imu0_remove_gravitational_acceleration: true
    pose0 : depth_sensor/raw
    pose0_config : [false, false, true,
                    false, false, false,
                    false,  false, false,
                    false, false, false,
                    false, false, false]