motor_controller:
  ros__parameters:
    enable_priorities: false
    num_motors: 3
    # Thrustrs in triangle formation
    #             0
    #            / \
    #           2   1
    
    # Directional Vectors
    # North(x)-East(y)-Down(z) Coordinate
    # Motor0 (CCW), Motor1(CCW), Motor2(CW)
    # No y or z motion with 3-thruster config
    # Assume value of 1 for triangle size, Center of gravity in middle of triangle
    # Assume thruster values at full power forward

    motor0:
      surge: 0.4641
      sway: 0.0 
      heave: 0.0 
      roll: 0.0 # N-m, assume very small
      pitch: -0.5359 
      yaw: 0.0 

    motor1:
      surge: 0.2679
      sway: 0.0
      heave: 0.0
      roll: 0.0
      pitch: 0.2679
      yaw: -1.0

    motor2:
      surge: 0.2679
      sway: 0.0
      heave: 0.0
      roll: 0.0
      pitch: 0.2679
      yaw: 1.0